spring:
  profiles:
    include: validation-properties, conversion-properties
  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      label: ${TENANT_ID}
  application:
    name: mars-palletizer-adapter
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_EMPTY
    serialization:
      write-date-keys-as-timestamps: false
      write-dates-as-timestamps: false
    time-zone: UTC
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  endpoint.logfile.external-file: ../logs/mars-palletizer-adapter.log
logging:
  config: classpath:log4j2-spring.yml
  file.name: mars-palletizer-adapter.log
kpi:
  sol:
    security:
      security-enabled: false
      client-id: RoboticsHub
      validate-client-id: true
      access-decision-map-type: MARS
      allowed-origins: http://localhost:4200, https://rh-web-app.azurewebsites.net
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: method